-- Write a query to display for each store its store ID, city, and country.
SELECT DISTINCT ST.STORE_ID, C.CITY, CO.COUNTRY
FROM SAKILA.STORE as ST
LEFT JOIN SAKILA.ADDRESS A
ON ST.ADDRESS_ID = A.ADDRESS_ID
LEFT JOIN SAKILA.CITY C
ON A.CITY_ID = C.CITY_ID
LEFT JOIN SAKILA.COUNTRY CO
ON C.COUNTRY_ID = CO.COUNTRY_ID
;
-- Write a query to display how much business, in dollars, each store brought in.
SELECT S.STORE_ID, SUM(P.AMOUNT) AS TOTAL_AMOUNT
FROM SAKILA.STORE S
LEFT JOIN SAKILA.STAFF ST ON S.STORE_ID = ST.STORE_ID
LEFT JOIN SAKILA.PAYMENT P ON ST.STAFF_ID = P.STAFF_ID
GROUP BY 1;

-- What is the average running time of films by category?
SELECT C.NAME AS CATEGORY, AVG(F.LENGTH) AS AVG_RUN_TIME
FROM SAKILA.FILM F
LEFT JOIN FILM_CATEGORY FC ON F.FILM_ID =  FC.FILM_ID
LEFT JOIN CATEGORY C ON FC.CATEGORY_ID = C.CATEGORY_ID
GROUP BY 1;

-- Which film categories are longest?
SELECT C.NAME AS CATEGORY, AVG(F.LENGTH) AS AVG_RUN_TIME
FROM SAKILA.FILM F
LEFT JOIN FILM_CATEGORY FC ON F.FILM_ID =  FC.FILM_ID
LEFT JOIN CATEGORY C ON FC.CATEGORY_ID = C.CATEGORY_ID
GROUP BY 1
ORDER BY 2 DESC
LIMIT 4;

-- Display the most frequently rented movies in descending order.
SELECT TITLE, COUNT(RENTAL_ID) AS RENTAL_COUNT
FROM SAKILA.FILM F
LEFT JOIN INVENTORY I ON F.FILM_ID = I.FILM_ID
LEFT JOIN RENTAL R ON I.INVENTORY_ID = R.INVENTORY_ID
GROUP BY 1
ORDER BY 2 DESC;

-- List the top five genres in gross revenue in descending order.
SELECT C.NAME AS CATEGORY, SUM(P.AMOUNT) AS GROSS_REVENUE
FROM SAKILA.CATEGORY C
LEFT JOIN SAKILA.FILM_CATEGORY FC ON C.CATEGORY_ID = FC.CATEGORY_ID
LEFT JOIN SAKILA.FILM F ON FC.FILM_ID = F.FILM_ID
LEFT JOIN SAKILA.INVENTORY I ON F.FILM_ID = I.FILM_ID
LEFT JOIN SAKILA.RENTAL R ON I.INVENTORY_ID = R.INVENTORY_ID
LEFT JOIN SAKILA.PAYMENT P ON R.RENTAL_ID = P.RENTAL_ID
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

-- Is "Academy Dinosaur" available for rent from Store 1?
SELECT * 
FROM SAKILA.INVENTORY I
LEFT JOIN FILM F ON I.FILM_ID = F.FILM_ID
LEFT JOIN STORE S ON I.STORE_ID = S.STORE_ID
WHERE F.TITLE = 'ACADEMY DINOSAUR' AND S.STORE_ID = 1;
